name: relic
description: Relic Notes app created for storing notes...
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  line_icons: ^0.2.0
  flutter_bloc: ^3.0.0
  http: ^0.12.0+3
  equatable: ^1.0.1
  rxdart: ^0.23.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          style: italic